name: Lint | Build | Deploy to Preview

on:
  push:
    branches-ignore:
      - main

env:
  NODE_LTS_VERSION: 18
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  lint_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node v${{ env.NODE_LTS_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          cache: "npm"
          check-latest: true

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          npm ci

      - name: Pull Vercel Environment Information
        run: |
          npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: |
          echo "Building..."
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Preview
        run: |
          echo "🎉 Deploying..."
          npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --no-wait
