name: Lint | Build | Deploy to Production

on:
  push:
    branches:
      - main

env:
  NODE_LTS_VERSION: 18
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  UPLOADTHING_SECRET: ${{ secrets.VERCEL_PROJECT_ID }}
  UPLOADTHING_APP_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
jobs:
  lint_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node v${{ env.NODE_LTS_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          check-latest: true
          cache: 'npm'

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          npm install

      - name: Install Vercel CLI
        run: | 
          echo "Installing Vercel CLI..."
          npm install --global vercel@latest

      - name: Run ESLint
        run: | 
          echo "Running ESLint..."
          npm run lint

      - name: Pull Vercel Environment Information
        run: | 
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: |
          echo "Building..."
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Production
        run: |
          echo "🎉 Deploying..."
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}